[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
known_django = "django"
known_rest_framework = "rest_framework"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_between_types = 1
lines_between_sections = 1
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = ["venv", ".git"]
