# Generated by Django 5.2.5 on 2025-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accoounts", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Vendor"), (2, "Customer")],
                default=2,
                null=True,
            ),
        ),
    ]
