# Generated by Django 5.2.5 on 2025-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accoounts", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="users/cover_photos/cover-photo-3.PNG",
                null=True,
                upload_to="users/cover_photos",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="users/profile_pictures/default.png",
                null=True,
                upload_to="users/profile_pictures",
            ),
        ),
    ]
